# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrentLocationGMS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrentLocationGMS
  pod 'GooglePlaces', '4.2.0'

  target 'CurrentLocationGMSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrentLocationGMSUITests' do
    # Pods for testing
  end

end
